// Code generated by evmbind. DO NOT EDIT.
package example

import (
	"math/big"
	"strings"

	"github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/vm/runtime"
)

var (
	_ = big.NewInt
)

var (
	ABI = "[{\"inputs\":[],\"name\":\"customAddress\",\"outputs\":[{\"internalType\":\"address\",\"name\":\"\",\"type\":\"address\"}],\"stateMutability\":\"view\",\"type\":\"function\"},{\"inputs\":[],\"name\":\"foo\",\"outputs\":[{\"internalType\":\"uint256\",\"name\":\"\",\"type\":\"uint256\"}],\"stateMutability\":\"pure\",\"type\":\"function\"},{\"inputs\":[{\"internalType\":\"uint256\",\"name\":\"a\",\"type\":\"uint256\"},{\"internalType\":\"uint256\",\"name\":\"b\",\"type\":\"uint256\"}],\"name\":\"mod\",\"outputs\":[{\"internalType\":\"uint256\",\"name\":\"\",\"type\":\"uint256\"}],\"stateMutability\":\"pure\",\"type\":\"function\"}]"
	Bin = "73000000000000000000000000636f6e7472616374301460806040526004361061004b5760003560e01c8063c298557814610050578063e347f2131461006e578063f43f523a1461008c575b600080fd5b6100586100bc565b6040516100659190610125565b60405180910390f35b6100766100c5565b6040516100839190610181565b60405180910390f35b6100a660048036038101906100a191906101cd565b6100f6565b6040516100b39190610125565b60405180910390f35b6000602a905090565b6000426040516020016100d8919061022e565b6040516020818303038152906040528051906020012060601c905090565b600081836101049190610278565b905092915050565b6000819050919050565b61011f8161010c565b82525050565b600060208201905061013a6000830184610116565b92915050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b600061016b82610140565b9050919050565b61017b81610160565b82525050565b60006020820190506101966000830184610172565b92915050565b600080fd5b6101aa8161010c565b81146101b557600080fd5b50565b6000813590506101c7816101a1565b92915050565b600080604083850312156101e4576101e361019c565b5b60006101f2858286016101b8565b9250506020610203858286016101b8565b9150509250929050565b6000819050919050565b6102286102238261010c565b61020d565b82525050565b600061023a8284610217565b60208201915081905092915050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601260045260246000fd5b60006102838261010c565b915061028e8361010c565b92508261029e5761029d610249565b5b82820690509291505056fea2646970667358221220c43ce8f088d6d3214820824e487df23dc3cd892110e6e9f2010cfde0c764185064736f6c634300080f0033"
)

// exec executes the given contract and method inside evm.
func exec(inputs []byte) []byte {
	code := common.Hex2Bytes(Bin)
	ret, _, err := runtime.Execute(code, inputs, nil)
	if err != nil {
		panic(err)
	}

	return ret
}

// CustomAddress is a function represented contract method 0xe347f213.
//
// Solidity: function customAddress() view returns(address)
func CustomAddress() common.Address {
	abis, err := abi.JSON(strings.NewReader(ABI))
	if err != nil {
		panic(err)
	}
	inputs, err := abis.Pack("customAddress")
	if err != nil {
		panic(err)
	}
	ret := exec(inputs)
	res, err := abis.Unpack("customAddress", ret)
	if err != nil {
		panic(err)
	}
	return res[0].(common.Address)
}

// Foo is a function represented contract method 0xc2985578.
//
// Solidity: function foo() pure returns(uint256)
func Foo() *big.Int {
	abis, err := abi.JSON(strings.NewReader(ABI))
	if err != nil {
		panic(err)
	}
	inputs, err := abis.Pack("foo")
	if err != nil {
		panic(err)
	}
	ret := exec(inputs)
	res, err := abis.Unpack("foo", ret)
	if err != nil {
		panic(err)
	}
	return res[0].(*big.Int)
}

// Mod is a function represented contract method 0xf43f523a.
//
// Solidity: function mod(uint256 a, uint256 b) pure returns(uint256)
func Mod(a *big.Int, b *big.Int) *big.Int {
	abis, err := abi.JSON(strings.NewReader(ABI))
	if err != nil {
		panic(err)
	}
	inputs, err := abis.Pack("mod", a, b)
	if err != nil {
		panic(err)
	}
	ret := exec(inputs)
	res, err := abis.Unpack("mod", ret)
	if err != nil {
		panic(err)
	}
	return res[0].(*big.Int)
}

